block_size_optimizer:
  ros__parameters:
    
    input_file: "/home/ryo/tukuba/tsukuba_all_241006_add-imu-conf.pcd"
    voxel_size: 0.1

    
    min_block_size: 10
    max_block_size: 11
    step_size: 1

    verbose: true
    run_once: true
