# PointCloud Compressor Preset Configurations

# High Quality Preset - Minimal compression, high accuracy
high_quality:
  ros__parameters:
    compression:
      voxel_size: 0.005      # Fine voxelization
      block_size: 4          # Small blocks for detail preservation
      use_8bit_indices: false # 16-bit indices for large dictionaries
    quality:
      target_compression_ratio: 0.7
      max_reconstruction_error: 0.0005
      validate_reconstruction: true

# Balanced Preset - Good compression with acceptable quality
balanced:
  ros__parameters:
    compression:
      voxel_size: 0.01       # Standard voxelization
      block_size: 8          # Standard block size
      use_8bit_indices: true # 8-bit indices for smaller files
    quality:
      target_compression_ratio: 0.4
      max_reconstruction_error: 0.001
      validate_reconstruction: false

# High Compression Preset - Maximum compression
high_compression:
  ros__parameters:
    compression:
      voxel_size: 0.02       # Coarse voxelization
      block_size: 16         # Large blocks for better compression
      use_8bit_indices: true # Always use 8-bit indices
    quality:
      target_compression_ratio: 0.2
      max_reconstruction_error: 0.005
      validate_reconstruction: false

# Fast Processing Preset - Optimized for speed
fast_processing:
  ros__parameters:
    compression:
      voxel_size: 0.015      # Moderate voxelization
      block_size: 8          # Standard block size
      use_8bit_indices: true # 8-bit indices
    performance:
      max_memory_mb: 2000    # Use more memory for speed
      num_threads: 0         # Use all available cores
      enable_profiling: true
    publishing:
      publish_once: false    # Continuous publishing
      publish_interval_ms: 1000

# Memory Constrained Preset - Low memory usage
memory_constrained:
  ros__parameters:
    compression:
      voxel_size: 0.02       # Coarser voxelization to reduce memory
      block_size: 4          # Smaller blocks to limit memory per operation
      use_8bit_indices: true # Always use 8-bit indices
    performance:
      max_memory_mb: 256     # Strict memory limit
      num_threads: 1         # Single thread to reduce memory overhead
    publishing:
      queue_size: 1          # Minimal queue size